
name: Deploy and Release

on:
  push:
    branches:
      - main

jobs:
  build-deploy-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust if you need a different version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        commit_message: 'Deploy to GitHub Pages'
        user_name: 'GitHub Action'
        user_email: 'action@github.com'
        force_orphan: true
